# Generated by Django 3.2.17 on 2023-02-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='about')),
                ('birthday', models.DateField()),
                ('bio', models.TextField(blank=True, null=True)),
                ('address', models.CharField(max_length=255)),
                ('zip_code', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=255)),
                ('projects', models.IntegerField(default=0)),
                ('awards', models.IntegerField(default=0)),
                ('customers', models.IntegerField(default=0)),
                ('cups_of_coffee', models.IntegerField(default=0)),
                ('cv', models.FileField(upload_to='about_cv')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('finish', models.DateField(null=True)),
                ('profession', models.CharField(max_length=250)),
                ('where', models.CharField(max_length=350)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=250)),
                ('profession', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=250)),
                ('percent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects')),
                ('link', models.URLField(blank=True, null=True)),
                ('profession', models.CharField(max_length=250)),
                ('category', models.ManyToManyField(blank=True, to='main.Category')),
            ],
        ),
    ]
